### ISSUE TITLE
Improved formatting of test results

### ISSUE THREAD

**Issue by hejops** [rattletat/homework-checker#6]
Test results are not displayed in a monospace font, making the output of long lists basically unreadable.

Additionally, a side-by-side "diff"-like view of current and expected output would facilitate detection of errors. Again, this is because the output of long lists is not very helpful in its current state.

**Comment by rattletat** [comment]
Your right, the output of long feedback results can be improved by using a monospace font.

The diff view is a bit more complex, since tracebacks are usually very complex and often don't contain any diff information at all (example are non-AssertionErrors such as SyntaxError etc.)

Since we use the Test Anything Protocol (TAP), one could possibly show a diff output if it is an AssertionError and it is not an test for None. One also has to check that the parser would work for all supported languages, e.g. testthat for R and pytest for Python.


Things to look into:
- [tap-diff](https://github.com/axross/tap-diff)
- [tap-difflet](https://github.com/namuol/tap-difflet)
